[package]
name = "agent-diva-gui"
version = "0.1.0"
description = "A Tauri App for Agent Diva"
authors = ["you"]
edition = "2021"

[lib]
name = "agent_diva_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { version = "0.11", features = ["json", "stream"] }
futures = "0.3"
eventsource-stream = "0.2"

dirs.workspace = true
